### ISSUE TITLE
Graphic on example has incorrect numbers

### ISSUE THREAD

**Issue by charlesdbecker** [learn-co-curriculum/introduction-to-derivatives#1]
It should say "x2 - x1 = 2 - 1 = 1" but instead says "x2 - x1 = 4 - 3 = 1"

Screenshot included with incorrect graphic that has correct numbers in explanation beneath it.

![screenshot of error](https://user-images.githubusercontent.com/12903057/48588555-35b19300-e8fd-11e8-90de-ea53c422009f.PNG)

**Comment by mas16** [comment]
Hi charlesdbecker! Thanks for the note. The figure has been corrected.
