### ISSUE TITLE
Missing Lesson in Curriculum: Gradient Descent Algorithms

### ISSUE THREAD

**Issue by befowle** [learn-co-curriculum/introduction-to-derivatives#2]
The Introduction to Derivatives lesson in the Data Science Math Interview Prep refers to a lesson on gradient descent algorithms, which is not listed in the curriculum:

![image](https://user-images.githubusercontent.com/52608396/61582175-41410380-aaf5-11e9-8ec9-9faefa744190.png)

The image below shows the Curriculum menu, where there is no prior lesson on gradient descent algorithms:
![image](https://user-images.githubusercontent.com/52608396/61582325-72bace80-aaf7-11e9-8fa5-6e2f9c006da0.png)

**Comment by mas16** [comment]
Hi befowle, the Technical Application - Data Science track you are in is an accelerated course that includes a subset of the lessons and labs from the regular course. Please contact admissions for information regarding access to additional lessons and labs. Thank you!
